refactor: создан сервис статистики
RybkinMike/java-explore-with-me pull request #3
Opened 2023-06-18 21:40 UTC by RybkinMike

2023-06-26 15:55 UTC, db-exp requested changes

2023-06-26 15:55 UTC, db-exp commented on stats/stats-dto/pom.xml
> +
предлагаю отформатировать, чтобы убрать пропуск строк

2023-06-26 15:55 UTC, db-exp commented on stats/stats-dto/pom.xml
> +        <dependency>
совсем не нужно для библиотеки с моделью

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/pom.xml
> +            <groupId>org.springframework.boot</groupId>
org.springframework.boot - неправильно, groupId тут твой

2023-06-26 15:55 UTC, db-exp commented on stats/stats-dto/Dockerfile
для dto не нужно собирать докер

2023-06-26 15:55 UTC, db-exp commented on stats/pom.xml
> +
вот тут не хватает groupId

2023-06-26 15:55 UTC, db-exp commented on stats/stats-client/pom.xml
> +        <groupId>org.springframework.boot</groupId>
тут parent идет из pom'а в корне stats, а не spring boot, то есть   <groupId></groupId> <artifactId>stats</artifactId>

2023-06-26 15:55 UTC, db-exp commented on stats/stats-client/pom.xml
> +            <groupId>org.postgresql</groupId>
а зачем клиенту база?

2023-06-26 15:55 UTC, db-exp commented on stats/stats-dto/pom.xml
> +        <dependency>
не используется

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/pom.xml
> +    <parent>
про parent тот же комментарий как для dto и client

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
не хочешь для него сделать dto и вынести в либу для модели?

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
На все String поля можно еще размер поставить

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsController.java
> +                                   @RequestParam(value = "uris", defaultValue = "") String[] uris,
Лучше кмк использовать List<String>

2023-06-26 15:55 UTC, db-exp commented on main-service/src/main/resources/application.properties
Не понял зачем в проперти база, main пока совсем пустой сервис

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/resources/application.properties
> +spring.datasource.username=root
можно и логин/пароль использовать из переменных среды

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
можно static

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +                listDTO.add(new StatsDTO("ewm-main-service", uris[i], repository.countByUriForUniqueIP(uris[i], from, to)));
давай попробуем переделать запрос к базе. Получать по одному не оптимально, нужно массив на вход и результат на выход

2023-06-26 15:55 UTC, db-exp commented on main-service/pom.xml
> +        <dependency>
тут пока не нужно

2023-06-26 15:55 UTC, db-exp commented on main-service/pom.xml
> +        <dependency>
тут пока не нужно

2023-06-26 15:55 UTC, db-exp commented on main-service/pom.xml
> +        <dependency>
тут пока не нужно

2023-06-26 15:55 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsController.java
> +    public List<StatsDTO> getStats(@RequestParam(value = "start") String start,
Может валидацию на параметры еще добавить? Базовую - не null, размер

2023-06-27 17:09 UTC, RybkinMike commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
Если честно, то я не понял. Ведь, для него уже есть StatsDTO? Не понимаю, зачем нужен еще один, по крайней мере на данном этапе.

2023-06-27 17:22 UTC, RybkinMike commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsController.java
> +    public List<StatsDTO> getStats(@RequestParam(value = "start") String start,
Я полагал, что я сам пишу клиента, поэтому валидировать входящие значения надо до их передачи, как мы делали в sherit в getway

2023-06-27 18:08 UTC, RybkinMike commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Нет, нельзя 😂. Чекстайл ошибку выдает

2023-06-28 22:11 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
ну почему же) если static final первым поставить вместо repository, тоже выдаст?

2023-06-28 22:15 UTC, db-exp requested changes

2023-06-28 22:15 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
Запутано получилось. У тебя в /hit входит Stats и выходит Stats, и , получается тогда там должен входить dto и выходить dto, а не модель с таблицей

2023-06-28 22:15 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
Либо как еще иногда делают - отдельный dto

2023-07-02 19:22 UTC, RybkinMike commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Все, получилось. Видимо, первый раз я что-то не так написал

2023-07-02 19:36 UTC, RybkinMike commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/Stats.java
> +public class Stats {
Теперь понял. Сделал отдельный dto на вход и выход. Но мне кажется, что можно было метод сделать void.

2023-07-03 07:18 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    StatsRepository repository;
private final

2023-07-03 07:20 UTC, db-exp approved these changes

2023-07-03 09:24 UTC, merged