Main svc
RybkinMike/java-explore-with-me pull request #4
Opened 2023-07-29 16:41 UTC by RybkinMike

2023-07-31 16:28 UTC, db-exp requested changes

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/model/compilation/Compilation.java
> +    @NotNull
и тут NotNull не нужен

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/model/compilation/NewCompilationDto.java
> +    @NotNull
тоже не обязательно - уже есть NotBlank

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/model/event/EventRequestDto.java
> +    @NotNull
тут тоже NotNull

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/model/user/UserDto.java
> +    @NotNull(message = "Имя не может быть пустым")
не нужно)

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/private1/PrivateServiceImpl.java
> +    LocationRepository locationRepository;
как и в других местах - лучше сервисы, чем репозитории

2023-07-31 16:28 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +        } catch (Exception ex) {
в общем случае лучше так не делать - будет сложно обнаружить ошибку

2023-07-31 16:28 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +        String start = "2000-01-01 01:01:01";
может лучше в константы?

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/public1/PublicServiceImpl.java
> +    CompilationMapper compilationMapper = new CompilationMapper();
писал выше - справедливо везде - лучше мапперы как статические методы

2023-07-31 16:28 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/public1/PublicController.java
давай пакет назовем как-то получше чем public1 и private1 - непонятно же)

2023-08-01 12:23 UTC, RybkinMike commented on main-service/src/main/java/ru/practicum/ewm/public1/PublicController.java
Поменял структуру проекта, мне кажется, что стало более понятно

2023-08-01 21:20 UTC, db-exp approved these changes

2023-08-02 07:27 UTC, merged